name: Fix linter hints

on: 
  workflow_call:
    inputs:
      workingdirectory:
        description: 'The root of the source tree which should be linted'
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: plugin/${{ inputs.workingdirectory }}
    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
      - name: Freeing up more disk space
        working-directory: /
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Checkout core repo
        uses: actions/checkout@v3
        with:
          repository: Graylog2/graylog2-server
          path: graylog2-server
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven
      - uses: actions/checkout@v2
        with:
          path: plugin
      - name: Set up Yarn cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('plugin/{0}/yarn.lock', inputs.workingdirectory)) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          path: ~/.cache/yarn
      - name: Build with Maven
        run: mvn -B --fail-fast -Pedantic -Dspotbugs.skip -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -DskipTests compile
        env:
          JAVA_OPTS: -Xmx6G
      - name: Reset yarn lockfile
        run: git checkout yarn.lock
        continue-on-error: true
      - name: Run lint --fix
        continue-on-error: true
        run: yarn lint --fix
      - name: Run lint:styles --fix
        continue-on-error: true
        run: yarn lint:styles --fix
      - name: Create/Update Pull Request
        uses: Graylog2/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
        with:
          path: plugin
          title: Fixing linter hints automatically
          body: This PR was created by a job that is running periodically to find and fix linter hints.
          author: Dr. Lint-a-lot <garybot2@graylog.com>
          branch: fix/linter-hints
          committer: Dr. Lint-a-lot <garybot2@graylog.com>
          commit-message: Running lint --fix
          delete-branch: true
