name: Fix linter hints

on: 
  workflow_call:
    inputs:
      workingdirectory:
        description: 'The root of the source tree which should be linted'
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: plugin/${{ inputs.workingdirectory }}

    steps:
      - name: Checkout core repo
        uses: actions/checkout@v3
        with:
          repository: Graylog2/graylog2-server
          path: graylog2-server
      - name: Prepare core repo
        working-directory: graylog2-server/graylog2-web-interface
        run: |
          yarn install
          yarn build
      - uses: actions/checkout@v2
        with:
          path: plugin
      - name: Set up Yarn cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('plugin/{0}/yarn.lock', inputs.workingdirectory)) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          path: ~/.cache/yarn
      - name: Install dependencies
        run: yarn install
      - name: Reset yarn lockfile
        run: git checkout yarn.lock
        continue-on-error: true
      - name: Run lint --fix
        continue-on-error: true
        run: yarn lint --fix
      - name: Create/Update Pull Request
        uses: Graylog2/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
        with:
          path: plugin
          title: Fixing linter hints automatically
          body: This PR was created by a job that is running periodically to find and fix linter hints.
          author: Dr. Lint-a-lot <garybot2@graylog.com>
          branch: fix/linter-hints
          committer: Dr. Lint-a-lot <garybot2@graylog.com>
          commit-message: Running lint --fix
          delete-branch: true
